//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anjali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int item_id { get; set; }
        public string item_name { get; set; }
        public decimal price { get; set; }
        public int cust_id { get; set; }
        public string cust_name { get; set; }
    }
}
